# Generated by Django 4.2.7 on 2023-11-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classSessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classSessionClassCode', models.IntegerField()),
                ('classSessionSessionCode', models.IntegerField()),
                ('classSessionStutus', models.CharField(max_length=10)),
                ('classSessionOpenTime', models.IntegerField()),
                ('classSessionOpenUntil', models.IntegerField()),
                ('classSessionHowManyUserDetect', models.IntegerField()),
                ('classSessionHowManyUserRecord', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sessionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionImageClassCode', models.IntegerField()),
                ('sessionImageSessionCode', models.IntegerField()),
                ('sessionImageImage', models.CharField(max_length=10000)),
                ('sessionImageTime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionLogClassCode', models.IntegerField()),
                ('sessionLogSessionCode', models.IntegerField()),
                ('sessionLogStdCode', models.IntegerField()),
                ('sessionLogFaceCode', models.IntegerField()),
                ('sessionLogFaceDes', models.CharField(max_length=6000)),
                ('sessionLogTime', models.IntegerField()),
            ],
        ),
    ]
