# Generated by Django 4.2.7 on 2023-11-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_classsessionmodel_sessionimage_sessionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='classHasActiveSession',
            field=models.BooleanField(default=False),
        ),
    ]
